---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: pretty
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Denuncias Eléctricas"
keywords:    "ingeniería, eléctrica"
tagline:     "Defendiendo los derechos del gremio"
description: "Denuncias Eléctricas"
source_link: "https://cieingenieros.github.io/denuncias"
google_analytics_key: UA-84763401-1  ## put YOUR key here to enable tracking! (blank to disable)

